FROM python:slim

ENV TECHLAND_AUTHZ_FLASK_ENV TECHLAND_AUTHZ_SECRET_KEY TECHLAND_AUTHZ_FLASK_DEBUG TECHLAND_AUTHZ_TIMEZONE TECHLAND_AUTHZ_DATABASE_URI TECHLAND_AUTHZ_USER_DEFAULT_ROLE TECHLAND_AUTHZ_USER_DEFAULT_EXPIRY_TIME TECHLAND_AUTHZ_USER_DEFAULT_STATUS  

EXPOSE 8080/tcp

WORKDIR opt/app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . . 

ARG GIT_COMMIT="nocommit"
ARG GIT_TAG="notag"
LABEL gitCommit=$GIT_COMMIT gitTag=$GIT_TAG

ENTRYPOINT ./start


