"""empty message

Revision ID: 1d0d4d896bbe
Revises: c05d62586538
Create Date: 2022-03-04 17:03:47.388056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d0d4d896bbe'
down_revision = 'c05d62586538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'last_active_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'last_change_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'failed_auth_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'failed_auth_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'last_change_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'last_active_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'last_login_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
